name: Actualizacion Automatica Portafolio

# Define cuándo se ejecuta el código
on:
  schedule:
    # Se ejecuta cada hora desde las 9:00 AM hasta las 5:00 PM (Hora RD)
    # 13-21 en UTC equivale a 09:00-17:00 en RD
    - cron: '0,30 13-21 * * 1-5'
  workflow_dispatch:
jobs:
  ejecutar-analisis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Copiar contenido del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install gspread google-auth yfinance pandas numpy

      - name: Crear archivo de credenciales JSON
        # Este paso toma el "Secret" que guardaste y lo convierte en el archivo que tu código busca
        run: echo '${{ secrets.GOOGLE_JSON_KEY }}' > principios.json

      - name: Ejecutar el script de Python
        run: python main.py
